package os;

import javax.swing.JLayeredPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author nugraha
 */
public class MainScreen extends javax.swing.JFrame {
    WsController wcon;

    /**
     * Creates new form NewJFrame
     */
    public MainScreen() {
        initComponents();
        wcon = new WsController(up1);
    }

    public WsController getWcon() {
        return wcon;
    }

    public void setWcon(WsController wcon) {
        this.wcon = wcon;
    }

    public GettingStarted getGettingStarted1() {
        return gettingStarted1;
    }

    public void setGettingStarted1(GettingStarted gettingStarted1) {
        this.gettingStarted1 = gettingStarted1;
    }

    public JLayeredPane getMsPanel() {
        return msPanel;
    }

    public void setMsPanel(JLayeredPane msPanel) {
        this.msPanel = msPanel;
    }

    public Ws getUp1() {
        return up1;
    }

    public void setUp1(Ws up1) {
        this.up1 = up1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msPanel = new javax.swing.JLayeredPane();
        up1 = new os.Ws();
        gettingStarted1 = new os.GettingStarted();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.black);

        msPanel.setBackground(new java.awt.Color(0, 0, 0));
        msPanel.setForeground(new java.awt.Color(204, 204, 204));
        msPanel.setPreferredSize(new java.awt.Dimension(800, 350));
        msPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        msPanel.add(up1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        javax.swing.GroupLayout gettingStarted1Layout = new javax.swing.GroupLayout(gettingStarted1);
        gettingStarted1.setLayout(gettingStarted1Layout);
        gettingStarted1Layout.setHorizontalGroup(
            gettingStarted1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        gettingStarted1Layout.setVerticalGroup(
            gettingStarted1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        msPanel.add(gettingStarted1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(msPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 509, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(msPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private os.GettingStarted gettingStarted1;
    private javax.swing.JLayeredPane msPanel;
    private os.Ws up1;
    // End of variables declaration//GEN-END:variables
}
