/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package os.view;

import javax.swing.JButton;

/**
 *
 * @author nugraha
 */
public class Landing extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Landing() {
        initComponents();
    }

    public Landing(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JButton getAutoBtn() {
        return autoBtn;
    }

    public void setAutoBtn(JButton autoBtn) {
        this.autoBtn = autoBtn;
    }

    public JButton getManButton() {
        return manButton;
    }

    public void setManButton(JButton manButton) {
        this.manButton = manButton;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        autoBtn = new javax.swing.JButton();
        manButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        autoBtn.setText("Auto");

        manButton.setText("Manual");

        jButton1.setText("Close");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(autoBtn)
                        .addGap(79, 79, 79)
                        .addComponent(manButton)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autoBtn)
                    .addComponent(manButton))
                .addGap(97, 97, 97)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton autoBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton manButton;
    // End of variables declaration//GEN-END:variables
}
