/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package os.view;

import javax.swing.JTabbedPane;
import os.Navigate;

/**
 *
 * @author nugraha
 */
public class ManualPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public ManualPanel() {
        initComponents();
    }

    public Classifying getClassifying1() {
        return classifying1;
    }

    public void setClassifying1(Classifying classifying1) {
        this.classifying1 = classifying1;
    }

    public File2Text getFile2Text1() {
        return file2Text1;
    }

    public void setFile2Text1(File2Text file2Text1) {
        this.file2Text1 = file2Text1;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }

    public POSTagging getpOSTagging2() {
        return pOSTagging1;
    }

    public void setpOSTagging2(POSTagging pOSTagging2) {
        this.pOSTagging1 = pOSTagging2;
    }

    public SelectingFiles getSelectingFiles1() {
        return selectingFiles1;
    }

    public void setSelectingFiles1(SelectingFiles selectingFiles1) {
        this.selectingFiles1 = selectingFiles1;
    }

    public Tokenizing getTokenizing1() {
        return tokenizing1;
    }

    public void setTokenizing1(Tokenizing tokenizing1) {
        this.tokenizing1 = tokenizing1;
    }

    public Visualizing getVisualizing1() {
        return visualizing1;
    }

    public void setVisualizing1(Visualizing visualizing1) {
        this.visualizing1 = visualizing1;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        selectingFiles1 = new os.view.SelectingFiles();
        file2Text1 = new os.view.File2Text();
        tokenizing1 = new os.view.Tokenizing();
        pOSTagging1 = new os.view.POSTagging();
        classifying1 = new os.view.Classifying();
        visualizing1 = new os.view.Visualizing();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        jTabbedPane1.addTab("Selecting Files", selectingFiles1);
        jTabbedPane1.addTab("Getting Text", file2Text1);
        jTabbedPane1.addTab("Tokenizing", tokenizing1);

        pOSTagging1.setPreferredSize(new java.awt.Dimension(413, 350));
        jTabbedPane1.addTab("POS Tagging", pOSTagging1);
        jTabbedPane1.addTab("Classifying", classifying1);
        jTabbedPane1.addTab("Visualizing", visualizing1);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private os.view.Classifying classifying1;
    private os.view.File2Text file2Text1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private os.view.POSTagging pOSTagging1;
    private os.view.SelectingFiles selectingFiles1;
    private os.view.Tokenizing tokenizing1;
    private os.view.Visualizing visualizing1;
    // End of variables declaration//GEN-END:variables
}
