/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package os.view;

/**
 *
 * @author nugraha
 */
public class ManualPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public ManualPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        selectingFiles1 = new os.view.SelectingFiles();
        file2Text1 = new os.view.File2Text();
        pOSTagging2 = new os.view.POSTagging();
        tokenizing1 = new os.view.Tokenizing();
        classifying1 = new os.view.Classifying();
        visualizing1 = new os.view.Visualizing();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N

        javax.swing.GroupLayout selectingFiles1Layout = new javax.swing.GroupLayout(selectingFiles1);
        selectingFiles1.setLayout(selectingFiles1Layout);
        selectingFiles1Layout.setHorizontalGroup(
            selectingFiles1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );
        selectingFiles1Layout.setVerticalGroup(
            selectingFiles1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Selecting Files", selectingFiles1);

        javax.swing.GroupLayout file2Text1Layout = new javax.swing.GroupLayout(file2Text1);
        file2Text1.setLayout(file2Text1Layout);
        file2Text1Layout.setHorizontalGroup(
            file2Text1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );
        file2Text1Layout.setVerticalGroup(
            file2Text1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Getting Text", file2Text1);

        pOSTagging2.setPreferredSize(new java.awt.Dimension(413, 350));
        jTabbedPane1.addTab("POS Tagging", pOSTagging2);

        javax.swing.GroupLayout tokenizing1Layout = new javax.swing.GroupLayout(tokenizing1);
        tokenizing1.setLayout(tokenizing1Layout);
        tokenizing1Layout.setHorizontalGroup(
            tokenizing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );
        tokenizing1Layout.setVerticalGroup(
            tokenizing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tokenizing", tokenizing1);

        javax.swing.GroupLayout classifying1Layout = new javax.swing.GroupLayout(classifying1);
        classifying1.setLayout(classifying1Layout);
        classifying1Layout.setHorizontalGroup(
            classifying1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );
        classifying1Layout.setVerticalGroup(
            classifying1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Classifying", classifying1);

        javax.swing.GroupLayout visualizing1Layout = new javax.swing.GroupLayout(visualizing1);
        visualizing1.setLayout(visualizing1Layout);
        visualizing1Layout.setHorizontalGroup(
            visualizing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );
        visualizing1Layout.setVerticalGroup(
            visualizing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Visualizing", visualizing1);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private os.view.Classifying classifying1;
    private os.view.File2Text file2Text1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private os.view.POSTagging pOSTagging2;
    private os.view.SelectingFiles selectingFiles1;
    private os.view.Tokenizing tokenizing1;
    private os.view.Visualizing visualizing1;
    // End of variables declaration//GEN-END:variables
}
